-- Generates a simplified view of the occurrences to allow efficient, repeated querying.
--
-- This template uses the following parameters
--   {{occurrence}} table
--   {{checklistKey}} for the taxonomy

SELECT
  gbifID,
  classificationDetails['{{checklistKey}}']['taxonkey'] AS taxonKey,
  classificationDetails['{{checklistKey}}']['specieskey'] AS speciesKey,
  decimalLatitude,
  decimalLongitude,
  year,
  month,
  recordedBy,
  recordedByID,
  basisOfRecord,
  scientificName,
  institutionCode,
  collectionCode,
  catalogNumber,
  datasetKey,
  datasetTitle,
  countryCode,
  mediaType,
  isSequenced,
  typeStatus,
  filter(
    array(
      -- this is expected to be relatively static but an enum or runtime API may be suitable if not
      named_struct('rank','domain',                 'id', classificationDetails['{{checklistKey}}']['domainkey'],                 'name', classificationDetails['{{checklistKey}}']['domain']),
      named_struct('rank','realm',                  'id', classificationDetails['{{checklistKey}}']['realmkey'],                  'name', classificationDetails['{{checklistKey}}']['realm']),
      named_struct('rank','kingdom',                'id', classificationDetails['{{checklistKey}}']['kingdomkey'],                'name', classificationDetails['{{checklistKey}}']['kingdom']),
      named_struct('rank','subkingdom',             'id', classificationDetails['{{checklistKey}}']['subkingdomkey'],             'name', classificationDetails['{{checklistKey}}']['subkingdom']),
      named_struct('rank','infrakingdom',           'id', classificationDetails['{{checklistKey}}']['infrakingdomkey'],           'name', classificationDetails['{{checklistKey}}']['infrakingdom']),
      named_struct('rank','phylum',                 'id', classificationDetails['{{checklistKey}}']['phylumkey'],                 'name', classificationDetails['{{checklistKey}}']['phylum']),
      named_struct('rank','subphylum',              'id', classificationDetails['{{checklistKey}}']['subphylumkey'],              'name', classificationDetails['{{checklistKey}}']['subphylum']),
      named_struct('rank','infraphylum',            'id', classificationDetails['{{checklistKey}}']['infraphylumkey'],            'name', classificationDetails['{{checklistKey}}']['infraphylum']),
      named_struct('rank','parvphylum',             'id', classificationDetails['{{checklistKey}}']['parvphylumkey'],             'name', classificationDetails['{{checklistKey}}']['parvphylum']),
      named_struct('rank','gigaclass',              'id', classificationDetails['{{checklistKey}}']['gigaclasskey'],              'name', classificationDetails['{{checklistKey}}']['gigaclass']),
      named_struct('rank','megaclass',              'id', classificationDetails['{{checklistKey}}']['megaclasskey'],              'name', classificationDetails['{{checklistKey}}']['megaclass']),
      named_struct('rank','superclass',             'id', classificationDetails['{{checklistKey}}']['superclasskey'],             'name', classificationDetails['{{checklistKey}}']['superclass']),
      named_struct('rank','class',                  'id', classificationDetails['{{checklistKey}}']['classkey'],                  'name', classificationDetails['{{checklistKey}}']['class']),
      named_struct('rank','subclass',               'id', classificationDetails['{{checklistKey}}']['subclasskey'],               'name', classificationDetails['{{checklistKey}}']['subclass']),
      named_struct('rank','infraclass',             'id', classificationDetails['{{checklistKey}}']['infraclasskey'],             'name', classificationDetails['{{checklistKey}}']['infraclass']),
      named_struct('rank','subterclass',            'id', classificationDetails['{{checklistKey}}']['subterclasskey'],            'name', classificationDetails['{{checklistKey}}']['subterclass']),
      named_struct('rank','superorder',             'id', classificationDetails['{{checklistKey}}']['superorderkey'],             'name', classificationDetails['{{checklistKey}}']['superorder']),
      named_struct('rank','order',                  'id', classificationDetails['{{checklistKey}}']['orderkey'],                  'name', classificationDetails['{{checklistKey}}']['order']),
      named_struct('rank','nanorder',               'id', classificationDetails['{{checklistKey}}']['nanorderkey'],               'name', classificationDetails['{{checklistKey}}']['nanorder']),
      named_struct('rank','suborder',               'id', classificationDetails['{{checklistKey}}']['suborderkey'],               'name', classificationDetails['{{checklistKey}}']['suborder']),
      named_struct('rank','infraorder',             'id', classificationDetails['{{checklistKey}}']['infraorderkey'],             'name', classificationDetails['{{checklistKey}}']['infraorder']),
      named_struct('rank','parvorder',              'id', classificationDetails['{{checklistKey}}']['parvorderkey'],              'name', classificationDetails['{{checklistKey}}']['parvorder']),
      named_struct('rank','section_zoology',        'id', classificationDetails['{{checklistKey}}']['section_zoologykey'],        'name', classificationDetails['{{checklistKey}}']['section_zoology']),
      named_struct('rank','subsection_zoology',     'id', classificationDetails['{{checklistKey}}']['subsection_zoologykey'],     'name', classificationDetails['{{checklistKey}}']['subsection_zoology']),
      named_struct('rank','superfamily',            'id', classificationDetails['{{checklistKey}}']['superfamilykey'],            'name', classificationDetails['{{checklistKey}}']['superfamily']),
      named_struct('rank','epifamily',              'id', classificationDetails['{{checklistKey}}']['epifamilykey'],              'name', classificationDetails['{{checklistKey}}']['epifamily']),
      named_struct('rank','family',                 'id', classificationDetails['{{checklistKey}}']['familykey'],                 'name', classificationDetails['{{checklistKey}}']['family']),
      named_struct('rank','subfamily',              'id', classificationDetails['{{checklistKey}}']['subfamilykey'],              'name', classificationDetails['{{checklistKey}}']['subfamily']),
      named_struct('rank','infrafamily',            'id', classificationDetails['{{checklistKey}}']['infrafamilykey'],            'name', classificationDetails['{{checklistKey}}']['infrafamily']),
      named_struct('rank','supertribe',             'id', classificationDetails['{{checklistKey}}']['supertribekey'],             'name', classificationDetails['{{checklistKey}}']['supertribe']),
      named_struct('rank','tribe',                  'id', classificationDetails['{{checklistKey}}']['tribekey'],                  'name', classificationDetails['{{checklistKey}}']['tribe']),
      named_struct('rank','subtribe',               'id', classificationDetails['{{checklistKey}}']['subtribekey'],               'name', classificationDetails['{{checklistKey}}']['subtribe']),
      named_struct('rank','infratribe',             'id', classificationDetails['{{checklistKey}}']['infratribekey'],             'name', classificationDetails['{{checklistKey}}']['infratribe']),
      named_struct('rank','genus',                  'id', classificationDetails['{{checklistKey}}']['genuskey'],                  'name', classificationDetails['{{checklistKey}}']['genus']),
      named_struct('rank','subgenus',               'id', classificationDetails['{{checklistKey}}']['subgenuskey'],               'name', classificationDetails['{{checklistKey}}']['subgenus']),
      named_struct('rank','section_botany',         'id', classificationDetails['{{checklistKey}}']['section_botanykey'],         'name', classificationDetails['{{checklistKey}}']['section_botany']),
      named_struct('rank','subsection_botany',      'id', classificationDetails['{{checklistKey}}']['subsection_botanykey'],      'name', classificationDetails['{{checklistKey}}']['subsection_botany']),
      named_struct('rank','series_botany',          'id', classificationDetails['{{checklistKey}}']['series_botanykey'],          'name', classificationDetails['{{checklistKey}}']['series_botany']),
      named_struct('rank','infrageneric_name',      'id', classificationDetails['{{checklistKey}}']['infrageneric_namekey'],      'name', classificationDetails['{{checklistKey}}']['infrageneric_name']),
      named_struct('rank','species_aggregate',      'id', classificationDetails['{{checklistKey}}']['species_aggregatekey'],      'name', classificationDetails['{{checklistKey}}']['species_aggregate']),
      named_struct('rank','species',                'id', classificationDetails['{{checklistKey}}']['specieskey'],                'name', classificationDetails['{{checklistKey}}']['species']),
      named_struct('rank','infraspecific_name',     'id', classificationDetails['{{checklistKey}}']['infraspecific_namekey'],     'name', classificationDetails['{{checklistKey}}']['infraspecific_name']),
      named_struct('rank','subspecies',             'id', classificationDetails['{{checklistKey}}']['subspecieskey'],             'name', classificationDetails['{{checklistKey}}']['subspecies']),
      named_struct('rank','infrasubspecific_name',  'id', classificationDetails['{{checklistKey}}']['infrasubspecific_namekey'],  'name', classificationDetails['{{checklistKey}}']['infrasubspecific_name']),
      named_struct('rank','proles',                 'id', classificationDetails['{{checklistKey}}']['proleskey'],                 'name', classificationDetails['{{checklistKey}}']['proles']),
      named_struct('rank','natio',                  'id', classificationDetails['{{checklistKey}}']['natiokey'],                  'name', classificationDetails['{{checklistKey}}']['natio']),
      named_struct('rank','aberration',             'id', classificationDetails['{{checklistKey}}']['aberrationkey'],             'name', classificationDetails['{{checklistKey}}']['aberration']),
      named_struct('rank','morph',                  'id', classificationDetails['{{checklistKey}}']['morphkey'],                  'name', classificationDetails['{{checklistKey}}']['morph']),
      named_struct('rank','variety',                'id', classificationDetails['{{checklistKey}}']['varietykey'],                'name', classificationDetails['{{checklistKey}}']['variety']),
      named_struct('rank','subvariety',             'id', classificationDetails['{{checklistKey}}']['subvarietykey'],             'name', classificationDetails['{{checklistKey}}']['subvariety']),
      named_struct('rank','form',                   'id', classificationDetails['{{checklistKey}}']['formkey'],                   'name', classificationDetails['{{checklistKey}}']['form']),
      named_struct('rank','subform',                'id', classificationDetails['{{checklistKey}}']['subformkey'],                'name', classificationDetails['{{checklistKey}}']['subform']),
      named_struct('rank','forma_specialis',        'id', classificationDetails['{{checklistKey}}']['forma_specialiskey'],        'name', classificationDetails['{{checklistKey}}']['forma_specialis']),
      named_struct('rank','lusus',                  'id', classificationDetails['{{checklistKey}}']['lususkey'],                  'name', classificationDetails['{{checklistKey}}']['lusus']),
      named_struct('rank','mutatio',                'id', classificationDetails['{{checklistKey}}']['mutatiokey'],                'name', classificationDetails['{{checklistKey}}']['mutatio'])
    ),
    x -> x.id IS NOT NULL AND x.id != ''
  ) AS lineage
FROM {{occurrence}}
